import { MovieClip } from "./clips.js";

// Dedicated 11 Indian Cinema Full Movies provided by user
export const INDIAN_MOVIES_LIST: MovieClip[] = [
  {
    id: "clip-indian-fool-n-final",
    movieId: 10001,
    movieTitle: "Fool N Final",
    clipTitle: "Full Bollywood Comedy Movie (HD) — Sunny Deol & Shahid Kapoor",
    videoUrl: "https://www.youtube.com/watch?v=dqDjZgwt9SQ",
    thumbnail: "https://img.youtube.com/vi/dqDjZgwt9SQ/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/dqDjZgwt9SQ/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/dqDjZgwt9SQ/maxresdefault.jpg",
    duration: "2:26:10",
    year: 2007,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Comedy", "Action", "Bollywood"],
    director: "Ahmed Khan",
    actors: ["Sunny Deol", "Shahid Kapoor", "Vivek Oberoi", "Bipasha Basu", "Ayesha Takia"],
    description: "Bollywood comedy blockbuster. A stolen 100-carat diamond leads to hilarious confusion, underground boxing, and high-speed car chases across Dubai.",
    views: 18450000,
    likes: 420000,
    rating: 8.8,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "fool n final", "sunny deol", "shahid kapoor", "comedy"],
    seo: {
      title: "Fool N Final - Full Bollywood Comedy Movie HD",
      description: "Watch Fool N Final full movie starring Sunny Deol, Shahid Kapoor and Vivek Oberoi.",
      keywords: ["Fool N Final", "Sunny Deol", "Shahid Kapoor", "Bollywood Full Movie"]
    }
  },
  {
    id: "clip-indian-ardh",
    movieId: 10002,
    movieTitle: "Ardh",
    clipTitle: "Full Romantic Drama Movie (HD) — Rajpal Yadav & Rubina Dilaik",
    videoUrl: "https://www.youtube.com/watch?v=SG0bvpT101c",
    thumbnail: "https://img.youtube.com/vi/SG0bvpT101c/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/SG0bvpT101c/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/SG0bvpT101c/maxresdefault.jpg",
    duration: "1:52:45",
    year: 2022,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Drama", "Romance", "Bollywood"],
    director: "Palash Muchhal",
    actors: ["Rajpal Yadav", "Rubina Dilaik", "Hiten Tejwani"],
    description: "Rajpal Yadav delivers an emotional tour-de-force as Shiva, a struggling theatre actor trying to make it big in Mumbai with the loving support of his wife Madhu.",
    views: 14200000,
    likes: 360000,
    rating: 8.6,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: false,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "ardh", "rajpal yadav", "rubina dilaik", "drama"],
    seo: {
      title: "Ardh - Full Romantic Drama Movie HD",
      description: "Watch Ardh full movie starring Rajpal Yadav and Rubina Dilaik.",
      keywords: ["Ardh Full Movie", "Rajpal Yadav", "Rubina Dilaik", "Bollywood"]
    }
  },
  {
    id: "clip-indian-ginna-bhai",
    movieId: 10003,
    movieTitle: "Ginna Bhai (Ginna)",
    clipTitle: "Action Comedy & Mystery Entertainer (Full Movie) — Vishnu Manchu & Sunny Leone",
    videoUrl: "https://www.youtube.com/watch?v=ClBNbdst_FU",
    thumbnail: "https://img.youtube.com/vi/ClBNbdst_FU/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/ClBNbdst_FU/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/ClBNbdst_FU/maxresdefault.jpg",
    duration: "2:08:20",
    year: 2022,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Comedy", "South Cinema"],
    director: "Suryaah",
    actors: ["Vishnu Manchu", "Sunny Leone", "Payal Rajput"],
    description: "Four childhood friends running a tent-house business get tangled into hilarious and paranormal chaos when an NRI girl arrives in their hometown.",
    views: 21300000,
    likes: 480000,
    rating: 8.4,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: false,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "ginna bhai", "vishnu manchu", "sunny leone", "comedy", "action"],
    seo: {
      title: "Ginna Bhai - Action Comedy Full Movie HD",
      description: "Watch Ginna Bhai full movie starring Vishnu Manchu, Sunny Leone and Payal Rajput.",
      keywords: ["Ginna Bhai", "Vishnu Manchu", "Sunny Leone", "South Hindi Dubbed Movie"]
    }
  },
  {
    id: "clip-indian-raja-raja-chora",
    movieId: 10004,
    movieTitle: "Raja Raja Chora",
    clipTitle: "Blockbuster Crime Comedy (Full Movie) — Sree Vishnu & Sunaina",
    videoUrl: "https://www.youtube.com/watch?v=DOurM9guaKA",
    thumbnail: "https://img.youtube.com/vi/DOurM9guaKA/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/DOurM9guaKA/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/DOurM9guaKA/maxresdefault.jpg",
    duration: "2:21:40",
    year: 2021,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Crime", "Comedy", "South Cinema"],
    director: "Hasith Goli",
    actors: ["Sree Vishnu", "Sunaina Yella", "Megha Akash"],
    description: "Bhaskar works at a xerox shop while pretending to be a software engineer, secretly burglarizing houses until an encounter with a clever police cop flips his life.",
    views: 16800000,
    likes: 510000,
    rating: 8.9,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "raja raja chora", "sree vishnu", "sunaina", "crime", "comedy"],
    seo: {
      title: "Raja Raja Chora - Blockbuster Crime Comedy Full Movie",
      description: "Watch Raja Raja Chora full movie starring Sree Vishnu and Megha Akash.",
      keywords: ["Raja Raja Chora", "Sree Vishnu", "Indian Movie", "Crime Comedy"]
    }
  },
  {
    id: "clip-indian-robbery-super",
    movieId: 10005,
    movieTitle: "Robbery (Super)",
    clipTitle: "High Tech Heist & Action Thriller (Full Movie) — Nagarjuna & Anushka Shetty",
    videoUrl: "https://www.youtube.com/watch?v=uQrTvCdEYi8",
    thumbnail: "https://img.youtube.com/vi/uQrTvCdEYi8/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/uQrTvCdEYi8/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/uQrTvCdEYi8/maxresdefault.jpg",
    duration: "2:31:15",
    year: 2005,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Thriller", "South Cinema"],
    director: "Puri Jagannadh",
    actors: ["Nagarjuna", "Anushka Shetty", "Sonu Sood", "Ayesha Takia"],
    description: "Two daring high-tech bike-racing thieves Akhil and Sonu pull off impossible heists across the globe until their deep brotherhood is tested.",
    views: 29500000,
    likes: 670000,
    rating: 8.7,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "robbery", "super", "nagarjuna", "anushka shetty", "sonu sood", "action"],
    seo: {
      title: "Robbery (Super) - Full Action Heist Movie HD",
      description: "Watch Robbery Super full movie starring Nagarjuna, Anushka Shetty and Sonu Sood.",
      keywords: ["Robbery Super", "Nagarjuna", "Anushka Shetty", "South Hindi Dubbed"]
    }
  },
  {
    id: "clip-indian-aag",
    movieId: 10006,
    movieTitle: "Aag",
    clipTitle: "Classic Bollywood Action & Emotional Drama (Full Movie) — Govinda & Shilpa Shetty",
    videoUrl: "https://www.youtube.com/watch?v=3A4mx0tTn7c",
    thumbnail: "https://img.youtube.com/vi/3A4mx0tTn7c/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/3A4mx0tTn7c/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/3A4mx0tTn7c/maxresdefault.jpg",
    duration: "2:38:00",
    year: 1994,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Drama", "Bollywood"],
    director: "K. Ravi Shankar",
    actors: ["Govinda", "Sonali Bendre", "Shilpa Shetty"],
    description: "Raju fights fearlessly against criminal kingpins and corrupt landlords to protect his family and his sister's dignity in this iconic Govinda action drama.",
    views: 38200000,
    likes: 850000,
    rating: 8.5,
    quality: "1080p HD",
    isTrending: false,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "aag", "govinda", "shilpa shetty", "action"],
    seo: {
      title: "Aag - Classic Bollywood Action Full Movie HD",
      description: "Watch Aag full movie starring Govinda, Shilpa Shetty and Sonali Bendre.",
      keywords: ["Aag Govinda", "Govinda Movies", "Bollywood Classic", "Full Movie"]
    }
  },
  {
    id: "clip-indian-thipparaa-meesam",
    movieId: 10007,
    movieTitle: "Thipparaa Meesam",
    clipTitle: "Intense Action Drama & Psychological Thriller (Full Movie) — Sree Vishnu & Nikki Tamboli",
    videoUrl: "https://www.youtube.com/watch?v=LQlJPgZBGpI",
    thumbnail: "https://img.youtube.com/vi/LQlJPgZBGpI/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/LQlJPgZBGpI/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/LQlJPgZBGpI/maxresdefault.jpg",
    duration: "2:28:10",
    year: 2019,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Drama", "South Cinema"],
    director: "Krishna Vijay",
    actors: ["Sree Vishnu", "Nikki Tamboli", "Rohini"],
    description: "Mani, an insomniac DJ addicted to substances and sports betting, locks horns with powerful bookies while dealing with childhood trauma.",
    views: 12900000,
    likes: 310000,
    rating: 8.3,
    quality: "1080p HD",
    isTrending: false,
    isMostWatched: false,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "thipparaa meesam", "sree vishnu", "nikki tamboli", "thriller"],
    seo: {
      title: "Thipparaa Meesam - Action Drama Full Movie HD",
      description: "Watch Thipparaa Meesam full movie starring Sree Vishnu and Nikki Tamboli.",
      keywords: ["Thipparaa Meesam", "Sree Vishnu", "South Dubbed Movie", "Indian"]
    }
  },
  {
    id: "clip-indian-don-no-1",
    movieId: 10008,
    movieTitle: "DON No. 1 (Don)",
    clipTitle: "Iconic Underworld Don Action Blockbuster (Full Movie) — Nagarjuna & Anushka Shetty",
    videoUrl: "https://www.youtube.com/watch?v=w_BEfT4sLEI",
    thumbnail: "https://img.youtube.com/vi/w_BEfT4sLEI/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/w_BEfT4sLEI/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/w_BEfT4sLEI/maxresdefault.jpg",
    duration: "2:34:50",
    year: 2007,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Crime", "South Cinema"],
    director: "Raghava Lawrence",
    actors: ["Nagarjuna", "Anushka Shetty", "Kelly Dorji"],
    description: "Suriya, the undisputed benevolent godfather of the city, clashes with international crime syndicate chief Feroz in a relentless war of power and justice.",
    views: 52000000,
    likes: 1400000,
    rating: 9.0,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "don no 1", "nagarjuna", "anushka shetty", "action", "south cinema"],
    seo: {
      title: "DON No. 1 - Underworld Action Blockbuster Full Movie HD",
      description: "Watch DON No. 1 full movie starring Nagarjuna, Anushka Shetty and Kelly Dorji.",
      keywords: ["DON No 1", "Nagarjuna", "Anushka Shetty", "Action Movie", "South Dubbed"]
    }
  },
  {
    id: "clip-indian-teri-meri-kahaani",
    movieId: 10009,
    movieTitle: "Teri Meri Kahaani",
    clipTitle: "Timeless Reincarnation Romance across 3 Eras (Full Movie) — Shahid Kapoor & Priyanka Chopra",
    videoUrl: "https://www.youtube.com/watch?v=-F9lj9GUrDQ",
    thumbnail: "https://img.youtube.com/vi/-F9lj9GUrDQ/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/-F9lj9GUrDQ/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/-F9lj9GUrDQ/maxresdefault.jpg",
    duration: "1:57:30",
    year: 2012,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Romance", "Drama", "Bollywood"],
    director: "Kunal Kohli",
    actors: ["Shahid Kapoor", "Priyanka Chopra"],
    description: "Two soulmates meet, fall in love, and are separated across three distinct eras: 1910 in Lahore, 1960 in Bombay, and 2012 in modern Nottingham.",
    views: 24600000,
    likes: 580000,
    rating: 8.6,
    quality: "1080p HD",
    isTrending: true,
    isMostWatched: false,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "teri meri kahaani", "shahid kapoor", "priyanka chopra", "romance"],
    seo: {
      title: "Teri Meri Kahaani - Full Romance Drama Movie HD",
      description: "Watch Teri Meri Kahaani full movie starring Shahid Kapoor and Priyanka Chopra.",
      keywords: ["Teri Meri Kahaani", "Shahid Kapoor", "Priyanka Chopra", "Bollywood Romance"]
    }
  },
  {
    id: "clip-indian-aladin",
    movieId: 10010,
    movieTitle: "Aladin",
    clipTitle: "Grand Fantasy Adventure (Full Movie) — Amitabh Bachchan, Sanjay Dutt & Jacqueline",
    videoUrl: "https://www.youtube.com/watch?v=1URZmiRNCgM",
    thumbnail: "https://img.youtube.com/vi/1URZmiRNCgM/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/1URZmiRNCgM/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/1URZmiRNCgM/maxresdefault.jpg",
    duration: "2:08:45",
    year: 2009,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Fantasy", "Adventure", "Bollywood"],
    director: "Sujoy Ghosh",
    actors: ["Amitabh Bachchan", "Sanjay Dutt", "Riteish Deshmukh", "Jacqueline Fernandez"],
    description: "Aladin Chatterjee rubs a magic lamp, unleashing a modern rock-star Genie Genius (Amitabh Bachchan) to win Jasmine's heart and defeat the evil Ringmaster (Sanjay Dutt).",
    views: 31000000,
    likes: 690000,
    rating: 8.5,
    quality: "1080p HD",
    isTrending: false,
    isMostWatched: true,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "aladin", "amitabh bachchan", "sanjay dutt", "fantasy"],
    seo: {
      title: "Aladin - Grand Fantasy Adventure Full Movie HD",
      description: "Watch Aladin full movie starring Amitabh Bachchan, Sanjay Dutt and Riteish Deshmukh.",
      keywords: ["Aladin Bollywood", "Amitabh Bachchan", "Sanjay Dutt", "Full Movie"]
    }
  },
  {
    id: "clip-indian-18-11-code-of-secrecy",
    movieId: 10011,
    movieTitle: "18.11: A Code of Secrecy",
    clipTitle: "Patriotic Cyber Action & Espionage Thriller (Full Movie) — Gulshan Grover & Prem Chopra",
    videoUrl: "https://www.youtube.com/watch?v=-ul7zXJsyDA",
    thumbnail: "https://img.youtube.com/vi/-ul7zXJsyDA/maxresdefault.jpg",
    poster: "https://img.youtube.com/vi/-ul7zXJsyDA/maxresdefault.jpg",
    backdrop: "https://img.youtube.com/vi/-ul7zXJsyDA/maxresdefault.jpg",
    duration: "2:03:10",
    year: 2014,
    genre: "Indian Cinema",
    genres: ["Indian Cinema", "Indian", "Action", "Mystery", "Bollywood"],
    director: "Mohibul Haque",
    actors: ["Rehal Khan", "Gulshan Grover", "Prem Chopra", "Asrani"],
    description: "A software prodigy invents breakthrough military surveillance software code-named 18.11, becoming targeted by international covert mercenaries and terror syndicates.",
    views: 9800000,
    likes: 210000,
    rating: 8.2,
    quality: "1080p HD",
    isTrending: false,
    isMostWatched: false,
    publishedAt: new Date().toISOString(),
    tags: ["indian", "bollywood", "18.11", "code of secrecy", "gulshan grover", "thriller"],
    seo: {
      title: "18.11: A Code of Secrecy - Patriotic Action Thriller Full Movie",
      description: "Watch 18.11 A Code of Secrecy full movie starring Gulshan Grover and Prem Chopra.",
      keywords: ["18.11 Code of Secrecy", "Gulshan Grover", "Prem Chopra", "Bollywood Action"]
    }
  }
];
